### ISSUE TITLE
Use guestFullName from VMware SDK for Virtual Machine platform field

### ISSUE THREAD

**Issue by klaver** [synackray/vcenter-netbox-sync#70] opened 2020-02-19 11:03 UTC
Currently the virtual machine platform vm_family variable is set based on two generic obj.guest.guestFamily categories, either Linux or Windows. To get more insight into the running versions, we rather have the obj.guest.guestFullName set as platform name

**Comment by synackray** [comment] 2020-02-19 11:06
I have vague memories that when originally exploring the VMware SDK models I found the `guest.guestFullName` to be quite inconsistent. This led to the generation of lots of unnecessary and duplicate entries.

Let me run this on a large instance with a couple thousand VMs and see what the data looks like. It's a very fair ask.

**Comment by klaver** [comment] 2020-02-19 11:13
Hi @synackray, before we discovered your brilliant python scripts, we used this PowerShell script which captured the guestFullName without any problems:
https://github.com/jwegner89/netbox-utilities/blob/master/Sync-Netbox.ps1

P.S. Our vCenter is running version 6.7, maybe things have improved recently?

**Comment by synackray** [comment] 2020-02-19 21:22
Hi @klaver! I ran this against a few vCenter instances today and here's what it pulled back. Both are running 6.5U1 or greater. What do you think? Do you prefer this level of platform detail?

```
2020-02-19 13:35:47,778 [INFO] Detected the following VM platforms for #70: 
{None: 3,
 'CentOS 4/5 or later (64-bit)': 4,
 'CentOS 7 (64-bit)': 22,
 'Debian GNU/Linux 9 (64-bit)': 79,
 'Microsoft Windows Server 2008 R2 (64-bit)': 12,
 'Microsoft Windows Server 2012 (64-bit)': 25,
 'Microsoft Windows Server 2016 or later (64-bit)': 43,
 'Other 3.x Linux (64-bit)': 1,
 'Red Hat Enterprise Linux 7 (64-bit)': 14,
 'Red Hat Enterprise Linux 8 (64-bit)': 55,
 'VMware Photon OS (64-bit)': 2}

2020-02-19 17:55:29,162 [INFO] Detected the following VM platforms for #70: 
{None: 412,
 '': 3,
 'CentOS 4/5 or later (32-bit)': 2,
 'CentOS 4/5 or later (64-bit)': 11,
 'CentOS 6 (64-bit)': 14,
 'CentOS 7 (64-bit)': 512,
 'Debian GNU/Linux 8 (64-bit)': 11,
 'Debian GNU/Linux 9 (64-bit)': 43,
 'Microsoft Windows 10 (64-bit)': 89,
 'Microsoft Windows 7 (64-bit)': 22,
 'Microsoft Windows 8.x (64-bit)': 56,
 'Microsoft Windows Server 2008 (64-bit)': 10,
 'Microsoft Windows Server 2008 R2 (64-bit)': 386,
 'Microsoft Windows Server 2012 (64-bit)': 1266,
 'Microsoft Windows Server 2016 or later (64-bit)': 276,
 'Oracle Linux 7 (64-bit)': 4,
 'Oracle Solaris 10 (64-bit)': 1,
 'Other (64-bit)': 1,
 'Other 2.6.x Linux (32-bit)': 1,
 'Other 2.6.x Linux (64-bit)': 2,
 'Other 3.x Linux (64-bit)': 51,
 'Other 4.x or later Linux (64-bit)': 2,
 'Other Linux (32-bit)': 2,
 'Other Linux (64-bit)': 3,
 'Red Hat Enterprise Linux 6 (32-bit)': 1,
 'Red Hat Enterprise Linux 6 (64-bit)': 249,
 'Red Hat Enterprise Linux 7 (64-bit)': 633,
 'Red Hat Enterprise Linux 8 (64-bit)': 31,
 'SUSE Linux Enterprise 11 (32-bit)': 12,
 'SUSE Linux Enterprise 11 (64-bit)': 12,
 'SUSE Linux Enterprise 12 (64-bit)': 12,
 'SUSE openSUSE (64-bit)': 14,
 'Ubuntu Linux (64-bit)': 38,
 'VMware Photon OS (64-bit)': 4}
```

**Comment by klaver** [comment] 2020-02-21 10:37
Yes, platform names exactly like that already exist in our NetBox configuration due to the previous PowerShell script

**Comment by synackray** [comment] 2020-02-21 20:08
I'll start writing this up and make sure it does not have any unexpected consequences. Thanks again for the suggestion. This looks much more reasonable than what I remember.

**Comment by synackray** [comment] 2020-02-25 12:14
Hi @klaver! Do you mind giving the latest commit in `70-detailed-vm-platforms` a spin to make sure it lines up to what you expect before I promote it? Thanks!

Example
![image](https://user-images.githubusercontent.com/24757919/75246728-a8800e00-57d0-11ea-9955-ea3b1405f75e.png)

**Comment by klaver** [comment] 2020-02-25 16:20
It seems to work properly, vms are now attached to their platform names. The only abnormality are the RHEL 8 vms where the vmtools somehow include the kernel versions (they also report exactly that string in the vCenter web-interface), I can live with that for now.

Current platform list in our NetBox setup now looks like:
CentOS 4/5 or later (64-bit)
CentOS 7 (64-bit)
Linux 4.18.0-147.0.3.el8_1.x86_64 Red Hat Enterprise Linux release 8.1 (Ootpa)
Linux 4.18.0-80.4.2.el8_0.x86_64 Red Hat Enterprise Linux release 8.0 (Ootpa)
Microsoft Windows 10 (64-bit)
Microsoft Windows 7 (64-bit)
Microsoft Windows Server 2008 R2 (64-bit)
Microsoft Windows Server 2012 (64-bit)
Microsoft Windows Server 2016 or later (64-bit)
Other 2.6.x Linux (64-bit)
Other 3.x Linux (64-bit)
Red Hat Enterprise Linux 5 (32-bit)
Red Hat Enterprise Linux 6 (64-bit)
Red Hat Enterprise Linux 7 (64-bit)
SunOS 5.10 (Solaris)
SUSE Linux Enterprise 11 (64-bit)
Ubuntu Linux (64-bit)
VMware ESXi
VMware Photon OS (64-bit)

**Comment by synackray** [comment] 2020-02-25 16:44
Thanks! I'll get this moved forward then. I appreciate all your feedback and helpful recommendations.

**Comment by synackray** [comment] 2020-02-25 17:04
Merged into `develop` and running through regression prior to being promoted to `master`.

**Closed by synackray** 2020-02-25 17:04 UTC
Labels: Priority: Low, Status: Completed, Type: Enhancement
