### ISSUE TITLE
Unable to collect necessary data for vCenter hosts

### ISSUE THREAD

**Issue by acaronmd** [synackray/vcenter-netbox-sync#82] opened 2020-02-26 19:16 UTC
### Environment
* Python version:  3.6.8
* NetBox version: 2.7.6
* vCenter version: 6.7.0
* vCenter NetBox Sync version:  develop - commit f539db3

### Steps to Reproduce
1. python run.py -v

### Expected Behavior
I'm expecting my vCenter hosts to sync, but there is an error.

### Observed Behavior

2020-02-26 12:11:51,332 [DEBUG] Received HTTP Status 200.
2020-02-26 12:11:51,332 [DEBUG] NetBox GET request OK; returned 200 status.
2020-02-26 12:11:51,333 [INFO] Comparison completed. 0 clusters orphaned NetBox objects did not match.
2020-02-26 12:11:51,333 [DEBUG] The following objects did not match: []
2020-02-26 12:11:51,334 [INFO] Initiated sync of vCenter host objects to NetBox.
2020-02-26 12:11:51,334 [INFO] Collecting vCenter host objects.
2020-02-26 12:11:51,350 [INFO] Collecting info about vCenter hosts 'esxihost1.example.local' object.
2020-02-26 12:11:51,535 [DEBUG] Collecting info to create NetBox manufacturers object.
2020-02-26 12:11:51,536 [DEBUG] Collecting info to create NetBox device_types object.
2020-02-26 12:11:51,536 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 12:11:51,623 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99375''object. Skipping.
2020-02-26 12:11:51,630 [INFO] Collecting info about vCenter hosts 'esxihost2.example.local' object.
2020-02-26 12:11:51,819 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 12:11:51,819 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 12:11:51,820 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 12:11:51,901 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99273''object. Skipping.
2020-02-26 12:11:51,907 [INFO] Collecting info about vCenter hosts 'esxihost3.example.local' object.
2020-02-26 12:11:52,075 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 12:11:52,075 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 12:11:52,076 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 12:11:52,159 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99578''object. Skipping.
2020-02-26 12:11:52,166 [INFO] Collecting info about vCenter hosts 'esxihost4.example.local' object.
2020-02-26 12:11:52,331 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 12:11:52,331 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 12:11:52,332 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 12:11:52,416 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99574''object. Skipping.
2020-02-26 12:11:52,420 [DEBUG] Collected 5 vCenter host objects.

**Comment by synackray** [comment] 2020-02-26 22:03
Hello @acaronmd! Are your ESXi Hosts defined inside a cluster within vCenter? The logs confirming whether vCenter clusters were found and synced would be a few lines before what was pasted. If not, that may be the issue. If so, then I may need to activate additional debug details to tell us exactly what failed in the VMware SDK.

**Comment by acaronmd** [comment] 2020-02-26 23:16
I've gone ahead and deleted my VMs, clusters and cluster groups, and tags. I've tried to sync again and I get the same error. I can send you more debugging data if you need it.

**Comment by synackray** [comment] 2020-02-26 23:22
Yes please. If you don't mind sending the full debug logs I'll see if something stands out. If you're concerned about sensitive data feel free to send the logs to my email directly: [One Time Private Note](https://privnote.com/Uo2dsZKa#64NhTZfRg)

**Comment by acaronmd** [comment] 2020-02-26 23:41
No problem. Logs have been sent.

**Comment by synackray** [comment] 2020-02-27 16:59
@acaronmd Thanks for the logs. You have a very interesting case and I really appreciate getting to see the details. I'm going to share the generic portions of the logs, with additional sanitization, so that the I can be certain my thought process makes sense.

During dependency checks the `vCenter` tag is searched for as it's a global dependency to all other objects. During your check an existing `vCenter` tag is detected. If I am reading the logs correctly, it is receiving the _wrong_ `vCenter` tag back, identified by slug `vcenter_1`.

```
2020-02-26 16:28:19,626 [DEBUG] Sending GET to 'https://netbox.example.com/api/extras/tags/?name=vcenter' with data 'None'.
2020-02-26 16:28:19,664 [DEBUG] Received HTTP Status 200.
2020-02-26 16:28:19,664 [DEBUG] NetBox GET request OK; returned 200 status.
2020-02-26 16:28:19,665 [DEBUG] NetBox tags object 'vcenter' already exists. Comparing values.
2020-02-26 16:28:19,665 [DEBUG] vc_data[name] and nb_data[name] values match.
2020-02-26 16:28:19,665 [DEBUG] Mismatch: vc_data[slug] value is 'vcenter' while nb_data[slug] value is 'vcenter_1'.
2020-02-26 16:28:19,666 [DEBUG] vc_data[slug] and nb_data[slug] values do not match.
2020-02-26 16:28:19,666 [INFO] NetBox tags object 'vcenter' do not match current values.
2020-02-26 16:28:19,666 [DEBUG] Sending PATCH to 'https://netbox.example.com/api/extras/tags/23/' with data '{'name': 'vcenter', 'slug': 'vcenter', 'comments': 'Objects synced from vCenter host vcenter. Be careful not to modify the name or slug.'}'.
2020-02-26 16:28:19,711 [DEBUG] Received HTTP Status 400.
2020-02-26 16:28:19,711 [WARNING] NetBox failed to modify tags object with status 400. The data sent may not be acceptable.
2020-02-26 16:28:19,712 [DEBUG] NetBox 400 status reason: {"slug":["tag with this Slug already exists."]}
2020-02-26 16:28:19,712 [DEBUG] Unaccepted request data: {'name': 'vcenter', 'slug': 'vcenter', 'comments': 'Objects synced from vCenter host vcenter. Be careful not to modify the name or slug.'}
2020-02-26 16:28:19,713 [INFO] Finished verifying prerequisites.
```

This result causes a snowball effect of problems. A key example is when the object orphaning occurs as shown below.

```
2020-02-26 16:28:20,031 [DEBUG] Sending GET to 'https://netbox.example.com/api/virtualization/clusters/?tag=vcenter' with data 'None'.
2020-02-26 16:28:20,144 [DEBUG] Received HTTP Status 200.
2020-02-26 16:28:20,144 [DEBUG] NetBox GET request OK; returned 200 status.
2020-02-26 16:28:20,145 [INFO] Comparison completed. 2 clusters orphaned NetBox objects did not match.
2020-02-26 16:28:20,145 [DEBUG] The following objects did not match: [{'id': 5, 'name': 'kangaroo.example.net', 'type': {'id': 3, 'url': 'https://netbox.example.com/api/virtualization/cluster-types/3/', 'name': 'VMware ESXi', 'slug': 'vmware-esxi'}, 'group': {'id': 3, 'url': 'https://netbox.example.com/api/virtualization/cluster-groups/3/', 'name': 'Amsterdam Datacenter', 'slug': 'amsterdam-datacenter'}, 'tenant': None, 'site': {'id': 7, 'url': 'https://netbox.example.com/api/dcim/sites/7/', 'name': 'Main Office', 'slug': 'mo'}, 'comments': '', 'tags': ['Synced', 'Orphaned', 'vCenter', 'vcenter'], 'custom_fields': {}, 'created': '2020-01-10', 'last_updated': '2020-02-26T22:43:58.819693Z', 'device_count': None, 'virtualmachine_count': 1}, {'id': 6, 'name': 'horse.example.net', 'type': {'id': 3, 'url': 'https://netbox.example.com/api/virtualization/cluster-types/3/', 'name': 'VMware ESXi', 'slug': 'vmware-esxi'}, 'group': {'id': 3, 'url': 'https://netbox.example.com/api/virtualization/cluster-groups/3/', 'name': 'Amsterdam Datacenter', 'slug': 'amsterdam-datacenter'}, 'tenant': None, 'site': {'id': 7, 'url': 'https://netbox.example.com/api/dcim/sites/7/', 'name': 'Main Office', 'slug': 'mo'}, 'comments': '', 'tags': ['Synced', 'Orphaned', 'vCenter', 'vcenter'], 'custom_fields': {}, 'created': '2020-01-10', 'last_updated': '2020-02-26T22:46:14.450849Z', 'device_count': None, 'virtualmachine_count': 26}]
2020-02-26 16:28:20,146 [INFO] Processing orphaned NetBox clusters 'kangaroo.example.net' object.
2020-02-26 16:28:20,147 [INFO] The clusters 'kangaroo.example.net' object has exceeded the 0 day max for orphaned objects. Sending it for deletion.
2020-02-26 16:28:20,147 [DEBUG] Sending DELETE to 'https://netbox.example.com/api/virtualization/clusters/5/' with data 'None'.
2020-02-26 16:28:20,232 [DEBUG] Received HTTP Status 409.
2020-02-26 16:28:20,233 [WARNING] Received 409 status when attemping to delete NetBox object (ID: 5). If you have more than 1 vCenter host configured this may be deleted on the final pass. Otherwise check the object dependencies.
2020-02-26 16:28:20,233 [DEBUG] NetBox 409 status body: {'detail': 'Unable to delete object. The following dependent objects were found: California-NY (virtualization.virtualmachine)'}
```
To sort this out I'm going to need to need to make a few changes. Let me begin by updating the logic for the dependencies check of tags. Note, this does not solve your original problem, which I'll speak to in the next post, but this has to be sorted before we can move on.

**Comment by acaronmd** [comment] 2020-02-27 17:05
Just wanted to note that the two vCenter (vcenter) and vcenter (vcenter_1) tags are created by the script, and recreated when I delete them.

**Comment by synackray** [comment] 2020-02-27 17:11
Would you mind sharing the output of the following URLs? I'd like to understand that better. Feel free to pass it to my e-mail. Thank you!

General:
https://yourdomain.com/api/extras/tags

vCenter Tag:
https://yourdomain.com/extras/tags/vcenter/changelog/

Other vCenter Tag:
https://yourdomain.com/extras/tags/vcenter_1/changelog/

**Comment by acaronmd** [comment] 2020-02-27 17:14
Email sent.

**Comment by synackray** [comment] 2020-02-27 17:51
Thank you! That gets me what I need. Let me fix the tagging and then sort out the original vCenter SDK issue. I checked the logs and this looks similar to #63 as the logs show the same behavior.

```
2020-02-26 16:28:20,015 [INFO] Collecting vCenter cluster objects.
2020-02-26 16:28:20,029 [DEBUG] Collected 1 vCenter cluster object.
2020-02-26 16:28:20,030 [INFO] Starting sync of 0 vCenter clusters objects to NetBox clusters objects.
2020-02-26 16:28:20,030 [INFO] Finished sync of 0 vCenter clusters objects to NetBox clusters objects.
2020-02-26 16:28:20,030 [INFO] Comparing existing NetBox clusters objects to current vCenter objects for pruning eligibility.
2020-02-26 16:28:20,031 [DEBUG] Sending GET to 'https://netbox.example.com/api/virtualization/clusters/?tag=vcenter' with data 'None'.
```

Can you confirm whether your vCenter is setup in an an organization structure similar to: vCenter > Cluster Group > Cluster > ESXi Hosts > Virtual Machines? Are there any ESXi hosts which reside outside of a cluster?

It would seem these hosts, which have obfuscated names that you can match in log timestamps or host IDs, are failing during object lookup. In #63 it was because they weren't assigned to a vCenter Cluster. I may need to write logic to handle this condition and provide more helpful errors.

```
2020-02-26 16:28:20,510 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 16:28:20,589 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99375''object. Skipping.
2020-02-26 16:28:20,594 [INFO] Collecting info about vCenter hosts 'couch.example.net' object.
2020-02-26 16:28:20,769 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 16:28:20,770 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 16:28:20,770 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 16:28:20,849 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99273''object. Skipping.
2020-02-26 16:28:20,855 [INFO] Collecting info about vCenter hosts 'kangaroo.example.net' object.
2020-02-26 16:28:21,015 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 16:28:21,015 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 16:28:21,016 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 16:28:21,095 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99578''object. Skipping.
2020-02-26 16:28:21,102 [INFO] Collecting info about vCenter hosts 'cheesecake.example.net' object.
2020-02-26 16:28:21,259 [DEBUG] Manufacturers object 'HP' already exists. Skipping.
2020-02-26 16:28:21,260 [DEBUG] Device Type object 'ProLiant DL360 Gen9' already exists. Skipping.
2020-02-26 16:28:21,260 [DEBUG] Collecting info to create NetBox devices object.
2020-02-26 16:28:21,338 [WARNING] Unable to collect necessary data for vCenter hosts ''vim.HostSystem:host-99574''object. Skipping.
2020-02-26 16:28:21,343 [DEBUG] Collected 5 vCenter host objects.
```

**Comment by acaronmd** [comment] 2020-02-27 19:11
We do not have any clusters created in our vCenter. We have 4 hosts setup like this:

vCenter > Datacenter > (4) ESXi Hosts > Virtual Machines

**Comment by synackray** [comment] 2020-02-27 20:25
OK this makes a lot of sense. I've committed a few changes to allow for more helpful logging of vCenter issues, sort out the tags, and handle ESXi Hosts without parent clusters.

Would you mind giving 16fe2eab90efdf3b5d924a3c63c58a51e0b5938c a shot and letting me know how it does?

**Comment by acaronmd** [comment] 2020-02-27 20:43
Results look similar if not the same. I've sent you new logs.

**Comment by synackray** [comment] 2020-02-27 20:48
Well we've made progress! The tags look cleaned up and the errors are more helpful for sure. 

```
2020-02-27 13:40:31,891 [WARNING] Unable to collect necessary data for vCenter hosts 'vim.HostSystem:host-99578'object. Received error: module 'settings' has no attribute 'ASSET_TAGS'
```
In the latest release of NetBox disabling the collection of asset tags was added as an optional setting. It appears that may be missing from your `settings.py`. Here is a snippet of the latest `settings.example.py`. 

```
# Optional Settings
# Attempt to collect asset tags from vCenter hosts
ASSET_TAGS = True
# Perform reverse DNS lookup on all eligible IP addresses and populate DNS name field in NetBox
POPULATE_DNS_NAME = True
# Use custom DNS servers defined below for reverse DNS lookups
CUSTOM_DNS_SERVERS = False
# List of DNS servers to query for PTR records
DNS_SERVERS = ["192.168.1.11", "192.168.1.12"]
# Create a custom field for virtual machines to track the current host they reside on
TRACK_VM_HOST = False
# Specify custom NetBox Device / vCenter Host role. Must match the name of an existing NetBox Device Role.
DEVICE_ROLE = "Server"
```

Would you mind adding the optional settings and trying again? I'll raise a new enhancement request to check settings and fail during prerequisite stages if they are missing.

**Comment by acaronmd** [comment] 2020-02-27 20:57
Done! Sending new logs.

**Comment by acaronmd** [comment] 2020-02-27 21:02
Just for the heck of it, I've just tried running the script with ASSET_TAGS set to False, but I get the same result. It errors out when creating the host, as it can't find the cluster with matching name to put it in.

**Comment by synackray** [comment] 2020-02-27 21:31
Thanks for sending the latest logs. Sorry for having to go through so many revisions.  I realize yet another reason why the script is getting tripped up now. It's honestly amazing the amount of use cases that would never cross your mind that may exist in the wild.

Outstanding issues

- Your vCenter FQDN is `vcenter.yourdomain.com` the tag shortner strips this to `vcenter` and that's what is causing the duplicate tags. I'll get that patched shortly.
- The host objects are not generating an attribute error like I originally thought, vCenter is instead responding the call by returning the object name itself as its own parent.. that doesn't make a great deal of sense, but I'll fix that.
- You've got an asset tag `'asset_tag': '                                '` that should be getting matched by the banned asset tag check, but somehow got passed to the object. I even manually confirmed it is a bad tag as shown below.

Standby for an upcoming commit.

```
>>> def is_banned_asset_tag(text):
...     """
...     Determines whether the text is a banned asset tag through various tests.
... 
...     :param text: Text to be checked against banned asset tags
...     :type text: str
...     :return: `True` if a banned asset tag else `False`
...     :rtype: bool
...     """
...     # Is asset tag in banned list?
...     text = text.lower()
...     banned_tags = [
...         "Default string", "NA", "N/A", "None", "Null", "Unknown", " ", ""
...         ]
...     banned_tags = [t.lower() for t in banned_tags]
...     if text in banned_tags:
...         result = True
...     # Does it exceed the max allowed length for NetBox asset tags?
...     elif len(text) > 50:
...         result = True
...     # Does asset tag contain all spaces?
...     elif text.replace(" ", "") == "":
...         result = True
...     # Apparently a "good" asset tag :)
...     else:
...         result = False
...     return result
... 
>>> at = '                                '
>>> is_banned_asset_tag(at)
True
>>> 
```

**Comment by synackray** [comment] 2020-02-27 23:23
@acaronmd I submitted patches for all of the issues. Would you mind giving 00006d3caca379378782046d29d7a79a7d7b15c0 a spin? Thanks again. You've been extremely patient and easy to work with.

**Comment by acaronmd** [comment] 2020-02-27 23:52
Thanks! I appreciate the work you're putting in to get this working. I find your script just as valuable as much as you do I'm sure.

I've sent new logs. More progress! Tags look good, hosts are being created now, but the VMs are not. You'll see in the logs. Also, I see the hosts are being assigned to the vCenter site, which prevents them from being racked in my actual sites. Not sure if the idea was to let it do an initial sync and then move it to the appropriate site. Thought it was worth mentioning tho.

**Comment by synackray** [comment] 2020-02-28 12:56
Thanks! I forgot about the VM to Cluster relationship.  This is a bit more challenging. Give me a few to sort it out.

Regarding the sites, the script places the vCenter site as a placeholder and you should then be allowed to overwrite it without fear of it being reverted. This is handled by a case in the `compare_dicts` function.

```
        elif dict1[key] != dict2[key]:
            log.debug(
                "Mismatch: %s value is '%s' while %s value is '%s'.",
                dict1_path, dict1[key], dict2_path, dict2[key]
                )
            # Allow the modification of device sites by ignoring the value
            if "site" in path and key == "name":
                log.debug("Site mismatch is allowed. Moving on.")
            else:
                result = False
```

**Comment by synackray** [comment] 2020-02-28 15:41
Alright I think I've got a reasonable way to sort this out. Unfortunately, I don't have a lab to mimic this in at this very moment. I'm requesting the resources so I don't have to rely on asking you to test, but would you mind running 1cb65ec and giving me your feedback? Thanks!

**Comment by acaronmd** [comment] 2020-02-28 15:50
@synackray I just tested, and now the VMs are failing to be created due to the cluster field missing. I've sent logs.

If there's the ability to sync tags from the host, could the script handle placing the hosts in the appropriate site/rack group/rack, if each host had all the necessary tags to do so?

**Comment by synackray** [comment] 2020-02-28 15:51
I don't know how I forgot that Virtual Machines require a cluster. That sort of defeats the entire model in this situation. NetBox is supposed to be a source of truth and if the ESXi hosts are not part of a cluster than there isn't a cluster to assign.

What are your thoughts on this? Would you be amenable if I defined a generic "Standalone ESXi Host" cluster?

**Comment by acaronmd** [comment] 2020-02-28 16:21
I would be okay with a generic cluster like you mentioned, or even perhaps to have a cluster for each standalone host based on its name.

**Comment by synackray** [comment] 2020-02-28 16:25
OK. The latter option is more challenging as the ESXi hosts are not clusters and will not appear when searching vCenter to determine clusters that should be orphaned. I'll think through that some and offer the generic cluster as an interim.

**Comment by acaronmd** [comment] 2020-02-28 16:31
Assigning all standalone ESXi hosts to a single "Standalone ESXi Host" cluster for a single vCenter instance would work, but would break over multiple vCenter instances, unless a "Standalone ESXi Host" cluster is created for each vCenter instance.

**Comment by synackray** [comment] 2020-02-28 16:41
In what way would it break? I'm struggling with the fact that it would be inaccurate, in the sense that the ESXi hosts and VMs are not part of a cluster, but I do not see a technical limitation.

**Comment by synackray** [comment] 2020-02-28 18:16
I was able to get resources allocated to replicate this. With commit 29b1a8b I am seeing hosts and VMs be properly assigned to the "Standalone ESXi Host" group. I'm running it through multi-vcenter instance tests and then full regression testing just to be certain.

![image](https://user-images.githubusercontent.com/24757919/75571606-d2983100-5a59-11ea-952c-7cb39d1ada81.png)

**Comment by acaronmd** [comment] 2020-02-28 18:45
I misunderstood the relationship between clusters and sites for "Standalone ESXi Hosts", as I was expecting the cluster to be assigned to a cluster group. Your last commit seems to have worked great!

**Comment by synackray** [comment] 2020-02-28 19:51
That's what I like to hear! I'll continue to do some testing and start moving this towards `develop` and eventually `master`. Thank you again for all your support.

**Closed** 2020-02-28 22:04 UTC
Labels: Priority: High, Status: Completed, Type: Bug
